runtime: nodejs10
service: amr-web

# [START handlers]
handlers:
  - url: /
    secure: always
    static_files: build/index.html
    upload: build/index.html

  - url: /portal
    secure: always
    static_files: build/index.html
    upload: build/index.html

  - url: /portal/(.*)
    secure: always
    static_files: build/\1
    upload: build/(.*)

  - url: /(.*)
    secure: always
    static_files: build/\1
    upload: build/(.*)
# [END handlers]

env_variables:
  NODE_ENV: production
  DEBUG: true
  API_URL: https://amr-travels.appspot.com/
